### ISSUE TITLE
Stop-limit ArgumentOutOfRangeException 

### ISSUE THREAD

**Issue by Dulatr** [dougdellolio/coinbasepro-csharp#138]
When trying to place a stop limit order I am receiving "System.ArgumentOutOfRangeException: Argument was outside the range of accepted values". I'm not sure if this is related to your library or not, but it reports _FixedSizeReader.cs is not located to view source on current call stack frame. With the snippet of code below getting executed twice, the stop orders are placed when viewing the site but my program crashes.

```
        private async void Bttn_Stop_Click(object sender, EventArgs e)
        {
            await client.OrdersService.CancelAllOrdersAsync();

            await client.OrdersService.PlaceStopOrderAsync(OrderSide.Sell, ProductType.BchUsd, 
                (decimal)0.01, (decimal)875, null);
        }
```

I just have a simple button that when clicked places the order at a predefined value. In the exception details it states that GDAXSharp is source of the exception. I've tried changing the order sides and the price by to no avail, ticker price is above the stop-sell I'm trying to place.

Thanks for the library by the way! I'm trying to learn the ropes, but getting stuck on this. :/

To note: all other order types work but Stop and Stop limit. I searched the CoreFx repository to manually point towards the FixedSizeReader.cs, which doesn't help that the debugger isn't catching on either of the Readpacket() lines. Same exception is thrown.

**Comment by dougdellolio** [comment]
@Dulatr I tried placing canceling orders and placing stop orders multiple times on a net core app and can’t seem to replicate this. Do you know at what exact point in this library the error is being thrown? Could it be something in the order response perhaps? Going to keep poking at it to see what I can find...

**Comment by Dulatr** [comment]
@dougdellolio I'm not sure where it's being thrown. There's no inner exception, but here are the details it's giving me. Hopefully this is useful: 
```System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Specified argument was out of the range of valid values.
  Source=GDAXSharp
  StackTrace:
   at GDAXSharp.WebSocket.WebSocket.WebSocket_MessageReceived(Object sender, MessageReceivedEventArgs e)
   at WebSocket4Net.WebSocket.FireMessageReceived(String message)
   at WebSocket4Net.Command.Text.ExecuteCommand(WebSocket session, WebSocketCommandInfo commandInfo)
   at WebSocket4Net.WebSocket.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
   at WebSocket4Net.WebSocket.client_DataReceived(Object sender, DataEventArgs e)
   at SuperSocket.ClientEngine.ClientSession.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.OnDataRead(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken) in f:\dd\NDP\fx\src\net\System\Net\_LazyAsyncResult.cs:line 415
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken) in f:\dd\NDP\fx\src\net\System\Net\_LazyAsyncResult.cs:line 368
   at System.Net.Security._SslStream.ProcessFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest) in f:\dd\NDP\fx\src\net\System\Net\SecureProtocols\_SslStream.cs:line 861
   at System.Net.Security._SslStream.ReadFrameCallback(AsyncProtocolRequest asyncRequest) in f:\dd\NDP\fx\src\net\System\Net\SecureProtocols\_SslStream.cs:line 1041
   at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result) in f:\dd\NDP\fx\src\net\System\Net\SecureProtocols\_HelperAsyncResults.cs:line 140
   at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes) in f:\dd\NDP\fx\src\net\System\Net\SecureProtocols\_FixedSizeReader.cs:line 124
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult) in f:\dd\NDP\fx\src\net\System\Net\SecureProtocols\_FixedSizeReader.cs:line 159
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken) in f:\dd\NDP\fx\src\net\System\Net\_LazyAsyncResult.cs:line 415
   at System.Net.ContextAwareResult.CompleteCallback(Object state) in f:\dd\NDP\fx\src\net\System\Net\_ContextAwareResult.cs:line 470
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken) in f:\dd\NDP\fx\src\net\System\Net\_ContextAwareResult.cs:line 463
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken) in f:\dd\NDP\fx\src\net\System\Net\_LazyAsyncResult.cs:line 368
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in f:\dd\NDP\fx\src\net\System\Net\Sockets\_BaseOverlappedAsyncResult.cs:line 385
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

**Comment by dougdellolio** [comment]
@Dulatr ahh I think i may know the problem here. This is coming from the websocket feed... not the placing of orders. are you using the websocket feed?

I believe you are receiving a response type that isn't defined. I have fixed that here so that an error isn't thrown if an unknown response type is received: https://github.com/dougdellolio/gdax-csharp/pull/133

if you are using the nuget package v1.0.18 that currently doesn't have this change in it. I will be releasing the next version with that change soon

**Comment by Dulatr** [comment]
Ah! Yes! I am using the websocket feed, if I just use the client I don't see the error! I am using the nuget package, which is great I can do that by the way, could a possible work around be to use client.productservices.gettickerpricesasync() while using a system timer? I was mainly using the websocket events for the live price data

**Comment by dougdellolio** [comment]
@Dulatr I just released next version. Update the nuget package to v1.0.19 for the fix. Let me know if you still see this happening. Thanks!

**Comment by Dulatr** [comment]
@dougdellolio Thanks so much! I just updated to the release, unfortunately I get a new error:
```Newtonsoft.Json.JsonReaderException: 'Could not convert string to decimal: 59866162f35ce600a4dad354. Path 'user_id', line 1, position 128.'``` But the order still appears on the site, albeit the quantity is not showing correct. Order gets posted but will entirety of funds rather that the set size.

**Comment by dougdellolio** [comment]
this problem exists in the `Activate` model here https://github.com/dougdellolio/gdax-csharp/blob/master/GDAXSharp/WebSocket/Models/Response/Activate.cs#L23

you will only see this if you are subscribed to the full channel. I will have this fixed for next release. For now if you are just looking for price data I would recommend just subscribing to `Ticker` channel.

i will take a look into the stop order later today when I have more time.

**Comment by dougdellolio** [comment]
are your stop orders actually going through with the incorrect amounts? I notice when I place a stop order in the sandbox the open order does show the wrong amount (entire funds) but when it actually goes through the sizes/prices are as specified. might be a problem with sandbox.... i haven't tried on live servers

**Comment by Dulatr** [comment]
I was testing this on live servers, so I haven't tried the sandbox on that note. Because I was testing them on the live server I wasn't letting them go through to see if it was correct or not. I will test with a small amount real quick to see.

**Comment by Dulatr** [comment]
yes, that is what I am seeing. holds entire funds, executes the correct size

**Comment by Dulatr** [comment]
Very strange. When I include the client library directly without NuGet I don't have this issue anymore. Maybe it's a package version issue from dependencies? I'll keep looking to see why this issue came up, if I find out I'll let you know so others won't suffer the same fate. :]

**Comment by dougdellolio** [comment]
if you are referring to `Could not convert string to decimal` its because I merged the change for that a day ago here https://github.com/dougdellolio/gdax-csharp/commit/60ffe3baf67fca8af81683bf82a34da130155479. i haven't released it to nuget yet 😃

**Comment by Dulatr** [comment]
Ah! I was referring to that, very nice! Appears to be working smooth here now. Thanks again for the work done on this project
